const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const UPDATE_CART = 'UPDATE_CART';
const ADD_PRODUCTS = 'UPDATE_PRODUCTS';
const UPDATE_PRODUCT_QTY = 'UPDATE_PRODUCT_QTY';

export {ADD_TO_CART, REMOVE_FROM_CART, UPDATE_CART, ADD_PRODUCTS, UPDATE_PRODUCT_QTY};